import Header from '@/components/widget/Header/page'
import './globals.css'
import dynamic from 'next/dynamic'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// const HeaderSSR = dynamic(()=> import("../components/widget/Header/page"), {ssr: false})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        </body>
    </html>
  )
}
